version: 2
enable-beta-ecosystems: true
updates:

  - package-ecosystem: "pub"
    directory: "/packages/api_client"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pub"
    directory: "/packages/blog_models"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pub"
    directory: "/packages/blog_newsletter_client"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pub"
    directory: "/packages/blog_repository"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pub"
    directory: "/blog_update_handler"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pub"
    directory: "/packages/butter_cms_client"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pub"
    directory: "/packages/captcha_client"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pub"
    directory: "/."
    schedule:
      interval: "weekly"

  - package-ecosystem: "pub"
    directory: "/packages/subscriptions_repository"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pub"
    directory: "/packages/template_engine"
    schedule:
      interval: "weekly"

