name: Template Engine Verify and Test

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    branches:
      - master
      - main
    paths:
      - ".github/workflows/template_engine_verify_and_test.yaml"
      - "packages/template_engine/**"

  push:
    branches:
      - master
      - main
    paths:
      - ".github/workflows/**"
      - "packages/template_engine/**"


jobs:
  verify_and_test:
    name: Verify and Test
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/dart_package.yml@main
    with:
      working_directory: packages/template_engine
      dart_sdk: stable
      min_coverage: 100
