name: Verify Github Actions

on:
  pull_request:
    branches:
      - master
      - main
  push:
    branches:
      - master
      - main

jobs:
  verify:
    name: Verify Mason Generator
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          cache: true
          cache-key: flutter-:os:-:channel:-:version:-:arch:-:hash:-$
          channel: stable
          flutter-version: 3.24.4

      - name: Install Mason
        run: dart pub global activate mason_cli

      - name: Install Very Good ClI
        run: dart pub global activate very_good_cli

      - name: Get Packages
        run: very_good packages get -r

      - name: Get Bricks
        run: mason add -g github_actions_dart

      - name: Test Github Actions Generation
        run: mason make github_actions_dart --on-conflict overwrite -c .github/workflows_config.json --set-exit-if-changed
